In [37]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import pandas as pd
from rich import print


In [30]:
def accuracy_metrics(y_test,y_pred):
    # Calculate the accuracy of the model
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy * 100:.2f}%")

    # Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(conf_matrix)

    # Classification Report
    class_report = classification_report(y_test, y_pred)
    print("Classification Report:")
    print(class_report)

In [4]:
# Load the wine dataset
wine = load_wine()

# Convert it into a pandas DataFrame
wine_df = pd.DataFrame(wine.data, columns=wine.feature_names)

# Add the target class labels (wine varieties) to the DataFrame
wine_df['target'] = wine.target

# Display the first few rows
print(wine_df.head())

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [5]:
print(wine_df.shape[0])

178

In [6]:
wine_df['target'].value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

In [15]:
X=wine_df[list(set(wine_df.columns)-set('target'))]
y=wine_df['target']

In [25]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistic regression

In [76]:
model = LogisticRegression()

# Fit the model to the training data
model.fit(X_train_scaled, y_train)

# Make predictions on the test data, to test the model
y_pred = model.predict(X_test_scaled)

In [77]:
accuracy_metrics(y_test,y_pred)

Accuracy: 100.00%

Confusion Matrix:

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

# SVM with RBF kernel

In [78]:
# Initialize the SVM model with RBF kernel
svm_rbf = SVC(kernel='rbf', gamma='scale', random_state=42)

# Train the model on the training data
svm_rbf.fit(X_train, y_train)
# Make predictions on the test set
y_pred = svm_rbf.predict(X_test)

# Show the predicted labels
print(f"Predicted labels: {y_pred}")

Predicted labels: [0 0 1 0 1 0 1 2 2 2 0 1 0 1 0 1 1 1 0 1 0 1 2 1 1 1 1 2 1 0 0 1 2 0 0 0]

In [79]:
accuracy_metrics(y_test,y_pred)

Accuracy: 77.78%

Confusion Matrix:

[[14  0  0]
 [ 0 11  3]
 [ 0  5  3]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.69      0.79      0.73        14
           2       0.50      0.38      0.43         8

    accuracy                           0.78        36
   macro avg       0.73      0.72      0.72        36
weighted avg       0.77      0.78      0.77        36

# Decision tree

In [80]:
# Initialize the Decision Tree classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Train the model on the training data
dt_classifier.fit(X_train, y_train)
# Make predictions on the test set
y_pred = dt_classifier.predict(X_test)

# Show the predicted labels
print(f"Predicted labels: {y_pred}")

Predicted labels: [0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1 0 1 0 1 1 2 2 2 1 1 1 0 0 1 2 0 0 0]

In [81]:
accuracy_metrics(y_test,y_pred)

Accuracy: 100.00%

Confusion Matrix:

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

# Random forests

In [82]:
# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [83]:
# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Show the predicted labels
print(f"Predicted labels: {y_pred}")

Predicted labels: [0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1 0 1 0 1 1 2 2 2 1 1 1 0 0 1 2 0 0 0]

In [84]:
accuracy_metrics(y_test,y_pred)

Accuracy: 100.00%

Confusion Matrix:

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

# Feedforward-NN

In [41]:
import torch
import torch.nn as nn
import torch.optim as optim

In [45]:
# Convert to PyTorch tensors
print(X_train_scaled.shape)
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)  # Long for classification
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

(142, 14)

In [54]:
len(y_train_tensor.unique())

3

## first FNN deisgn

In [55]:
class FeedforwardNN(nn.Module):
    def __init__(self):
        super(FeedforwardNN, self).__init__()
        
        # Input layer (64 neurons), first hidden layer (32 neurons), output layer (3 classes)
        self.fc1 = nn.Linear(X_train_tensor.shape[1], 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, len(y_train_tensor.unique()))  # 3 output classes (Wine types)
        
        # ReLU activation function
        self.relu = nn.ReLU()
        
    def forward(self, x):
        # x = self.relu(self.fc1(x))
        x=self.fc1(x)
        x = self.relu(self.fc2(x))
        #x=self.fc2(x)
        x = self.fc3(x)
        return x

In [56]:
# Initialize the model
model = FeedforwardNN()

# Loss function: CrossEntropyLoss for multi-class classification
criterion = nn.CrossEntropyLoss()

# Optimizer: Adam optimizer
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [57]:
# Number of epochs for training
epochs = 100

# Training loop
for epoch in range(epochs):
    model.train()  # Set the model to training mode
    
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass: Compute predicted y by passing X to the model
    y_pred = model(X_train_tensor)
    
    # Compute the loss
    loss = criterion(y_pred, y_train_tensor)
    
    # Backward pass: Compute gradient of the loss with respect to model parameters
    loss.backward()
    
    # Update the model parameters using the optimizer
    optimizer.step()
    
    # Print loss for every 10th epoch
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

Epoch 10/100, Loss: 0.8857

Epoch 20/100, Loss: 0.6384

Epoch 30/100, Loss: 0.4220

Epoch 40/100, Loss: 0.2606

Epoch 50/100, Loss: 0.1579

Epoch 60/100, Loss: 0.0990

Epoch 70/100, Loss: 0.0666

Epoch 80/100, Loss: 0.0480

Epoch 90/100, Loss: 0.0363

Epoch 100/100, Loss: 0.0285

In [58]:
# Set the model to evaluation mode
model.eval()

# Make predictions on the test set
with torch.no_grad():  # No need to calculate gradients during evaluation
    y_pred = model(X_test_tensor)
    _, predicted = torch.max(y_pred, 1)  # Get the class with the highest score

In [59]:
# Evaluate the model using accuracy
accuracy = accuracy_score(y_test_tensor, predicted)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test_tensor, predicted)
print("Confusion Matrix:")
print(conf_matrix)

# Classification Report
class_report = classification_report(y_test_tensor, predicted)
print("Classification Report:")
print(class_report)

Accuracy: 100.00%

Confusion Matrix:

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

## second FNN design
- batchnormalization & dropout
- no activation function

In [70]:

class WineNet(nn.Module):
    def __init__(self, input_size, hidden1=128, hidden2=64, dropout_rate=0.3, num_classes=3):
        super(WineNet, self).__init__()
        
        self.fc1 = nn.Linear(input_size, hidden1)
        self.bn1 = nn.BatchNorm1d(hidden1)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout_rate)

        self.fc2 = nn.Linear(hidden1, hidden2)
        self.bn2 = nn.BatchNorm1d(hidden2)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout_rate)

        self.fc3 = nn.Linear(hidden2, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu1(x)
        x = self.dropout1(x)

        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu2(x)
        x = self.dropout2(x)

        x = self.fc3(x)  # Output layer, no activation
        return x

In [71]:
# Initialize the model
model = WineNet(X_train_tensor.shape[1])

# Loss function: CrossEntropyLoss for multi-class classification
criterion = nn.CrossEntropyLoss()

# Optimizer: Adam optimizer
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [72]:
# Number of epochs for training
epochs = 100

# Training loop
for epoch in range(epochs):
    model.train()  # Set the model to training mode
    
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass: Compute predicted y by passing X to the model
    y_pred = model(X_train_tensor)
    
    # Compute the loss
    loss = criterion(y_pred, y_train_tensor)
    
    # Backward pass: Compute gradient of the loss with respect to model parameters
    loss.backward()
    
    # Update the model parameters using the optimizer
    optimizer.step()
    
    # Print loss for every 10th epoch
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

Epoch 10/100, Loss: 0.4374

Epoch 20/100, Loss: 0.2503

Epoch 30/100, Loss: 0.1699

Epoch 40/100, Loss: 0.1249

Epoch 50/100, Loss: 0.0855

Epoch 60/100, Loss: 0.0598

Epoch 70/100, Loss: 0.0533

Epoch 80/100, Loss: 0.0407

Epoch 90/100, Loss: 0.0344

Epoch 100/100, Loss: 0.0322

In [73]:
# Set the model to evaluation mode
model.eval()

# Make predictions on the test set
with torch.no_grad():  # No need to calculate gradients during evaluation
    y_pred = model(X_test_tensor)
    _, predicted = torch.max(y_pred, 1)  # Get the class with the highest score

In [74]:
# Evaluate the model using accuracy
accuracy = accuracy_score(y_test_tensor, predicted)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test_tensor, predicted)
print("Confusion Matrix:")
print(conf_matrix)

# Classification Report
class_report = classification_report(y_test_tensor, predicted)
print("Classification Report:")
print(class_report)

Accuracy: 100.00%

Confusion Matrix:

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36